# SAM makefile BuildMethod 目標(由 gen 產)。sam build 會呼叫 build-<LogicalId>。
# 每個 Lambda = 一顆 Go bootstrap(provided.al2023/arm64)。

build-FnAdminActivities:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminAdmins:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminAnalysis:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminDashboardGetStats:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminLogin:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminLogs:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminModeration:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminPointHistory:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminPushAll:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminUsers:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminVersions:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAdminVouchers:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAnalytics:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAppLogin:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAppRegister:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAppVersionConfig:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatArchiver:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatGetHistory:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatGetRoomInfo:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatGetRooms:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatGetUploadUrl:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatMarkRead:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatWsConnect:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatWsDisconnect:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnChatWsSendMessage:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityAddComment:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityCreatePost:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityGetPostDetail:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityGetPosts:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityGetUploadUrl:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityGetUserPosts:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityLikeComment:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCommunityLikePost:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCreateGame:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnDailyBonus:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnEventCommands:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnGameDetail:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnGameRegister:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnGetRatings:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnEventGetUploadUrl:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnGetUploadUrl:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnLedger:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnMyGames:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnNotifications:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnRedeemCode:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnRedeemPoints:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnRejectRegistration:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnAcceptRegistration:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCancelGame:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnCancelRegistration:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnSearchGames:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnSubmitRating:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnSubscribePush:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnSubscriptionStatus:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnUnsubscribePush:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnClaimPushBonus:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnUserComments:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnUserInfo:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnUserProfile:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnVapidKey:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .

build-FnVerifyUser:
	GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags='-s -w' -o $(ARTIFACTS_DIR)/bootstrap .
